version: 2.1
orbs:
  ruby: circleci/ruby@1.0.4
jobs:
  build:
    docker:
      - image: cimg/ruby:3.2.1
    steps:
      - checkout
      - ruby: ruby --version
      - run:
          name: Publish gem to Rubygems
          command: |
            echo "Hello world"
workflows:
  version: 2.1
  my-workflow:
     jobs:
       - build
