version: 2.1
orbs:
  ruby: circleci/ruby@1.4.0
jobs:
  build:
    docker:
      - image: cimg/ruby:3.1.0
    executor: ruby/default
    steps:
      - checkout
      - run:
        name: which bundler?
        command: bundler -v
      - ruby/bundle-install
workflows:
  version: 2.1
  my-workflow:
    jobs:
      - build
